chore: update readme to take into account new space regions
storyblok/storyblok-js pull request #413
Opened 2023-12-11 16:43 UTC by manuelschroederdev

With the recent addition of the server locations in Canada and Australia, the readme needs to be updated.

2023-12-11 17:05 UTC, fgiuliani approved these changes

2023-12-13 12:49 UTC, alexjoverm approved these changes

2023-12-13 12:53 UTC, alexjoverm requested changes
Hi @manuelschroederdev - the PR is all good, but I can't approve it as @storyblok/js is not yet using latest version of https://github.com/storyblok/storyblok-js-client with the new changes for the new regions. So better to hold on the docs.

@fgiuliani let's work on coordinating the js-client update across SDKs

2024-01-10 14:05 UTC, fgiuliani commented
I think we can close this PR, as the changes were already applied to the README file:

https://github.com/storyblok/storyblok-js/commit/e6ce028e81d37bc7ee5ece1d475191b963e17bad#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R79

2024-01-10 14:05 UTC, closed without merging